# This is a workflow that will automatically sync your Peloton rides with Garmin

name: üîÑ Sync Workflow

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      workoutsToDownload:
        type: number
        default: "5"
      saveLocalCopy:
        type: boolean
        default: false
  schedule:
    - cron: '0 1 * * *'

env:
  OUTPUT_DIR: /app/output

jobs:
  sync:
    name: üîÑ Sync
    runs-on: ubuntu-latest
    container: 
      image:  philosowaffle/peloton-to-garmin:console-stable
      options: --user root
    steps:

    - name: üìÅCreate output directory
      run: mkdir -p ${{ env.OUTPUT_DIR }}

    - name: üóÉ Create config file
      env:
        DEFAULT_WORKOUT_NUM: 25
      run: |
        cat <<EOT > /app/configuration.local.json 
        {
          "App": {
            "EnablePolling": false,
            "CheckForUpdates": true,
            "CloseConsoleOnFinish": true
          },
          "Format": {
            "Fit": true,
            "Json": false,
            "Tcx": false,
            "SaveLocalCopy": ${{ github.event.inputs.saveLocalCopy || false }},
            "IncludeTimeInHRZones": false,
            "IncludeTimeInPowerZones": false,
            "StackedWorkouts": {
              "AutomaticallyStackWorkouts": false,
              "MaxAllowedGapSeconds": 300
            }
          },
          "Peloton": {
            "Email": "${{ secrets.PELOTON_USERNAME }}",
            "Password": "${{ secrets.PELOTON_PASSWORD }}",
            "NumWorkoutsToDownload": ${{ github.event.inputs.workoutsToDownload || env.DEFAULT_WORKOUT_NUM }}
          },
          "Garmin": {
            "Email": "${{ secrets.GARMIN_USERNAME }}",
            "Password": "${{ secrets.GARMIN_PASSWORD }}",
            "Upload": true,
            "FormatToUpload": "fit"
          },

          "Observability": {
            "Prometheus": {
              "Enabled": false
            },
            "Jaeger": {
              "Enabled": false
            },
            "Serilog": {
              "Using": [ "Serilog.Sinks.Console"],
              "MinimumLevel": "Information"
            }
          }
        }
        EOT
    
    - name: Run P2G Sync
      shell: bash
      run: |
          set -e
          dotnet /app/ConsoleClient.dll \
            --configurationFile "/app/configuration.local.json" \
            --outputDirectory "/app/output" \

    - name: ‚§¥ Upload output directory
      uses: actions/upload-artifact@v4
      if: ${{ github.event.inputs.saveLocalCopy == 'true' }}
      with:
        name: output
        path: ${{ env.OUTPUT_DIR }}
        if-no-files-found: error






